x86Build:
  image: 192.168.81.5:5000/builder
  user: root
  working_dir: /root/tvmod
  privileged: true
  net: "host"
  volumes:
    - "$HOME/working:/root"
    - "/mnt/sourcetgz:/mnt/sourcetgz"
    - "/mnt/pub:/mnt/pub"
    - "/etc/localtime:/etc/localtime"
    - "/etc/timezone:/etc/timezone"
  command: /usr/bin/linux32 ./build-all.sh -q NasX86.4.2.1.tgz -a arm
